name: qycli-nginx
base: core20
adopt-info: qycli-nginx
summary: NGINX for qycli
description: |
  Mainline NGINX with some extra modules for qycli
  Licence: https://github.com/nginx/nginx/blob/master/docs/text/LICENSE

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  qycli-nginx:
    command: usr/local/nginx/sbin/nginx

parts:
  qycli-nginx:
    plugin: autotools
    override-pull: |
      add-apt-repository -y ppa:maxmind/ppa

      # Download NGINX
      ngxLatestVer=$(curl 'http://nginx.org/download/' | grep -oP 'href="nginx-\K[0-9]+\.[0-9]+\.[0-9]+' | sort -t. -rn -k1,1 -k2,2 -k3,3 | head -1)
      snapcraftctl set-version "${ngxLatestVer}"
      curl "http://nginx.org/download/nginx-${ngxLatestVer}.tar.gz" > $SNAPCRAFT_PROJECT_DIR/nginx-latest.tar.gz

      ## Copy ready command from project dir to bin
      #cp -rf $SNAPCRAFT_PROJECT_DIR/ready-command bin/ready-command
      #chmod +x bin/ready-command

      # Download Dependencies and Modules and unpack them to sources/
      chmod +x $SNAPCRAFT_PROJECT_DIR/nginx-sources-pull
      $SNAPCRAFT_PROJECT_DIR/nginx-sources-pull

      snapcraftctl pull

    source: $SNAPCRAFT_PROJECT_DIR/nginx-latest.tar.gz
    override-build: |
      snapcraftctl build
      
      cp -rf /usr/local/luajit/ $SNAPCRAFT_PART_INSTALL/usr/local/luajit/
      
      make -C sources/modules/lua_resty_core install PREFIX=/usr/local/nginx
      make -C sources/modules/lua_resty_lrucache install PREFIX=/usr/local/nginx
      
    build-packages:
      - software-properties-common
      - curl
      - wget
      - libgd-dev
      - libgeoip-dev
      - libpcre3-dev
      - libperl-dev
      - libssl-dev
      - libxslt-dev
      - lsb-release
      - zlib1g-dev
      - tar
      - unzip
      - libpq-dev
      - libpam0g-dev
      - uuid-dev
      - mmdb-bin
      - libmaxminddb0
      - libmaxminddb-dev
    autotools-configure-parameters:
      - --with-ld-opt="-Wl,-rpath,/usr/local/luajit/lib"
      - --with-cc-opt="-Wno-error"
      - --conf-path=/etc/nginx/nginx.conf
      - --http-log-path=/var/log/nginx/access.log
      - --error-log-path=/var/log/nginx/error.log
      - --lock-path=/var/lock/nginx.lock
      - --pid-path=/run/nginx.pid
      - --http-fastcgi-temp-path=/var/lib/nginx/fastcgi
      - --http-proxy-temp-path=/var/lib/nginx/proxy
      - --http-scgi-temp-path=/var/lib/nginx/scgi
      - --http-uwsgi-temp-path=/var/lib/nginx/uwsgi
      - --with-compat
      - --with-openssl=sources/dependencies/openssl
      - --with-openssl-opt=enable-ec_nistp_64_gcc_128
      - --with-openssl-opt=no-weak-ssl-ciphers
      - --with-pcre=sources/dependencies/pcre
      - --with-pcre-jit
      - --with-zlib=sources/dependencies/zlib
      - --with-http_ssl_module
      - --with-http_stub_status_module
      - --with-http_realip_module
      - --with-http_auth_request_module
      - --with-http_dav_module
      - --with-http_slice_module
      - --with-threads
      - --with-file-aio
      - --with-http_addition_module
      - --with-http_flv_module
      - --with-http_gunzip_module
      - --with-http_gzip_static_module
      - --with-http_image_filter_module=dynamic
      - --with-http_mp4_module
      - --with-http_random_index_module
      - --with-http_secure_link_module
      - --with-http_sub_module
      - --with-http_xslt_module=dynamic
      - --with-mail=dynamic
      - --with-mail_ssl_module
      - --with-stream
      - --with-stream_ssl_module
      - --with-stream_ssl_preread_module
      - --add-dynamic-module=sources/modules/ngx_cache_purge
      - --add-dynamic-module=sources/modules/ngx_headers_more
      - --add-dynamic-module=sources/modules/ngx_http_auth_pam_module
      - --add-dynamic-module=sources/modules/nginx-dav-ext-module
      - --add-dynamic-module=sources/modules/ngx_devel_kit
      - --add-dynamic-module=sources/modules/echo_nginx_module
      - --add-dynamic-module=sources/modules/ngx-fancyindex
      - --add-dynamic-module=sources/modules/lua-nginx-module
      - --add-dynamic-module=sources/modules/nchan
      - --add-dynamic-module=sources/modules/nginx-rtmp-module
      - --add-dynamic-module=sources/modules/nginx-upload-progress-module
      - --add-dynamic-module=sources/modules/ngx_http_substitutions_filter_module
      - --add-dynamic-module=sources/modules/ngx_http_geoip2_module
