name: qycli-nginx
adopt-info: nginx
summary: NGINX for qycli
description: "Mainline NGINX with some extra modules"

grade: devel
confinement: devmode

apps:
  nginx:

parts:
  nginx:
    plugin: autotools
    override-pull: |
      add-apt-repository -y ppa:maxmind/ppa

      ngxLatestVer=$(curl 'http://nginx.org/download/' | grep -oP 'href="nginx-\K[0-9]+\.[0-9]+\.[0-9]+' | sort -t. -rn -k1,1 -k2,2 -k3,3 | head -1)
      snapcraftctl set-version "${ngxLatestVer}"

      # Download NGINX
      curl "http://nginx.org/download/nginx-${ngxLatestVer}.tar.gz" > nginx-latest.tar.gz

      mkdir nginx-latest
      tar zxvf nginx-latest.tar.gz --strip-components=1 -C nginx-latest

    source: nginx-latest.tar.gz
    build-packages:
      - libgd-dev
      - libgeoip-dev
      - libpcre3-dev
      - libperl-dev
      - libssl-dev
      - libxslt1-dev
      - lsb-release
      - zlib1g-dev
      - libluajit-5.1-dev
      - tar
      - libpq-dev
      - libpam0g-dev
      - uuid-dev
      - libmaxminddb-dev
    configflags:
      - --with-http_ssl_module
      - --with-http_realip_module
      - --with-http_addition_module
      - --with-http_sub_module
      - --with-http_gunzip_module
      - --with-http_gzip_static_module
      - --with-http_random_index_module
      - --with-http_secure_link_module
      - --with-http_stub_status_module
      - --with-http_auth_request_module
      - --with-http_xslt_module=dynamic
      - --with-http_image_filter_module=dynamic
      - --with-http_geoip_module=dynamic
      - --with-stream=dynamic
      - --with-stream_ssl_module
      - --with-stream_ssl_preread_module
      - --with-stream_geoip_module=dynamic
      - --with-http_perl_module=dynamic
      - --with-mail=dynamic
      - --with-mail_ssl_module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/njs/nginx
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_pagespeed
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/headers-more-nginx-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/lua-nginx-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/naxsi/naxsi_src/
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-length-hiding-filter-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/Session-Binding-Proxy/nginx_session_binding_proxy_module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_devel_kit
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_http_upstream_order
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/rds-json-nginx-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/testcookie-nginx-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_brotli
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_postgres
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nchan
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_http_auth_pam_module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/echo-nginx-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-upstream-fair
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_cache_purge
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx-fancyindex
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-upload-progress-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_http_substitutions_filter_module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/graphite-nginx-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-module-vts
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-ct
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-rtmp-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-ts-module
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-module-sts
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/nginx-module-stream-sts
      - --add-dynamic-module=$SNAPCRAFT_STAGE/modules/ngx_http_geoip2_module
      - --with-threads
      - --with-http_slice_module
      - --with-file-aio
      - --with-http_v2_module
    organize:
      sbin: bin
